import React, { useState } from 'react';
import { aiSynthesize, aiGaps, aiReview } from '../services/api';
export default function AgentsPage() {
  const [tab, setTab] = useState('synthesize'); const [loading, setLoading] = useState(false); const [result, setResult] = useState(null);
  const [inputs, setInputs] = useState({ papers: 'Attention Is All You Need (Vaswani 2017), BERT (Devlin 2018), GPT-4 Technical Report (OpenAI 2023), Chain-of-Thought Prompting (Wei 2022), LoRA (Hu 2022)', topic: 'Evolution of Transformer-based Language Models',
    field: 'Large Language Models and Reasoning', existing: 'Current research covers in-context learning, chain-of-thought prompting, and RLHF alignment. Most work focuses on English language.',
    review_topic: 'Efficient Fine-tuning Methods for Large Language Models', papers_summary: 'LoRA, QLoRA, Adapter layers, Prefix tuning, Prompt tuning - 15 papers from 2021-2024', scope: 'comprehensive' });
  const renderResult = (obj, depth = 0) => {
    if (!obj) return null; if (typeof obj === 'string') return <p style={{ color: '#e0e0e0', lineHeight: 1.6, whiteSpace: 'pre-wrap' }}>{obj}</p>;
    if (Array.isArray(obj)) return <div style={{ marginLeft: depth * 12 }}>{obj.map((item, i) => <div key={i} style={{ background: '#1a1a2e', padding: 12, borderRadius: 8, marginBottom: 8, borderLeft: '3px solid #e94560' }}>{typeof item === 'object' ? renderResult(item, depth + 1) : <span style={{ color: '#e0e0e0' }}>{String(item)}</span>}</div>)}</div>;
    return <div style={{ marginLeft: depth * 12 }}>{Object.entries(obj).map(([k, v]) => <div key={k} style={{ marginBottom: 12 }}><div style={{ color: '#e94560', fontSize: 13, fontWeight: 'bold', textTransform: 'uppercase', marginBottom: 4 }}>{k.replace(/_/g, ' ')}</div>{typeof v === 'object' && v !== null ? renderResult(v, depth + 1) : <div style={{ color: '#e0e0e0', background: '#1a1a2e', padding: '8px 12px', borderRadius: 6 }}>{typeof v === 'number' ? <span style={{ color: '#2ecc71', fontWeight: 'bold', fontSize: 18 }}>{v}</span> : typeof v === 'boolean' ? <span style={{ color: v ? '#2ecc71' : '#e94560', fontWeight: 'bold' }}>{v ? 'Yes' : 'No'}</span> : String(v)}</div>}</div>)}</div>;
  };
  const run = async () => { setLoading(true); setResult(null); try { let r; if (tab === 'synthesize') r = await aiSynthesize({ papers: inputs.papers, topic: inputs.topic }); else if (tab === 'gaps') r = await aiGaps({ field: inputs.field, existing_research: inputs.existing }); else r = await aiReview({ topic: inputs.review_topic, papers_summary: inputs.papers_summary, scope: inputs.scope }); setResult(r); } catch { setResult({ error: 'Failed' }); } setLoading(false); };
  const tabs = [{key:'synthesize',label:'🔬 Synthesize'},{key:'gaps',label:'🔍 Find Gaps'},{key:'review',label:'📝 Generate Review'}];
  return (<div><h1 style={{ color: '#fff', marginBottom: 20 }}>AI Research Agents</h1>
    <div style={{ display: 'flex', gap: 8, marginBottom: 24 }}>{tabs.map(t => (<button key={t.key} onClick={() => { setTab(t.key); setResult(null); }} style={{ padding: '10px 20px', background: tab === t.key ? '#e94560' : '#16213e', color: tab === t.key ? '#fff' : '#ccc', border: '1px solid #0f3460', borderRadius: 8, cursor: 'pointer' }}>{t.label}</button>))}</div>
    <div style={{ background: '#16213e', padding: 24, borderRadius: 12, marginBottom: 20 }}>
      {tab === 'synthesize' && <>{[{k:'papers',l:'Papers (titles/authors)'},{k:'topic',l:'Topic'}].map(f => (<div key={f.k} style={{marginBottom:12}}><label style={{color:'#ccc',fontSize:13}}>{f.l}</label><textarea value={inputs[f.k]} onChange={e=>setInputs({...inputs,[f.k]:e.target.value})} rows={3} style={{width:'100%',padding:10,background:'#1a1a2e',border:'1px solid #0f3460',borderRadius:6,color:'#fff',marginTop:4,resize:'vertical',boxSizing:'border-box'}} /></div>))}</>}
      {tab === 'gaps' && <>{[{k:'field',l:'Research Field'},{k:'existing',l:'Existing Research Summary'}].map(f => (<div key={f.k} style={{marginBottom:12}}><label style={{color:'#ccc',fontSize:13}}>{f.l}</label><textarea value={inputs[f.k]} onChange={e=>setInputs({...inputs,[f.k]:e.target.value})} rows={3} style={{width:'100%',padding:10,background:'#1a1a2e',border:'1px solid #0f3460',borderRadius:6,color:'#fff',marginTop:4,resize:'vertical',boxSizing:'border-box'}} /></div>))}</>}
      {tab === 'review' && <>{[{k:'review_topic',l:'Review Topic'},{k:'papers_summary',l:'Papers Summary'},{k:'scope',l:'Scope'}].map(f => (<div key={f.k} style={{marginBottom:12}}><label style={{color:'#ccc',fontSize:13}}>{f.l}</label><input value={inputs[f.k]} onChange={e=>setInputs({...inputs,[f.k]:e.target.value})} style={{width:'100%',padding:10,background:'#1a1a2e',border:'1px solid #0f3460',borderRadius:6,color:'#fff',marginTop:4,boxSizing:'border-box'}} /></div>))}</>}
      <button onClick={run} disabled={loading} style={{ padding: '12px 30px', background: loading ? '#888' : '#e94560', color: '#fff', border: 'none', borderRadius: 6, cursor: loading ? 'not-allowed' : 'pointer', marginTop: 8 }}>{loading ? '⏳ Processing...' : '🚀 Run AI'}</button>
    </div>
    {result && <div style={{ background: '#16213e', padding: 24, borderRadius: 12 }}><h3 style={{ color: '#e94560', marginTop: 0 }}>Results</h3>{renderResult(result)}</div>}
  </div>);
}
